- name: Update and upgrade OS
  apt:
    update_cache: yes
    upgrade: dist

- name: Install base packages
  apt:
    name:
      - python3
      - python3-pip
      - net-tools
      - curl
      - vim
      - git
      - chrony
      - openvswitch-switch
      - ovn-central
      - ovn-host
      - wget
    state: present

- name: Add user "{{ new_user }}"
  user:
    name: "{{ new_user }}"
    password: "{{ new_user_password }}"
    shell: /bin/bash
    groups: sudo
    append: yes

    - name: Add user kolla
      user:
        name: kolla
        shell: /bin/bash
        groups: sudo
        append: yes
        create_home: yes

    - name: Allow passwordless sudo for kolla user
      copy:
        dest: /etc/sudoers.d/kolla
        content: "kolla ALL=(ALL) NOPASSWD:ALL\n"
        mode: '0440'

    - name: Set hostname (optional)
      hostname:
        name: "{{ inventory_hostname }}"
