- hosts: compute
  become: true
  tasks:
    - name: Add td-agent repository
      apt_repository:
        repo: 'deb http://packages.treasuredata.com/4/ubuntu/focal/ focal contrib'
        state: present
        filename: 'treasure-data'

    - name: Add td-agent GPG key
      apt_key:
        url: https://packages.treasuredata.com/GPG-KEY-td-agent
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install td-agent
      apt:
        name: td-agent
        state: present

    - name: Configure td-agent to forward logs
      copy:
        dest: /etc/td-agent/td-agent.conf
        content: |
          <source>
            @type tail
            path /var/log/syslog
            pos_file /var/log/td-agent/syslog.pos
            tag system.syslog
            format syslog
          </source>

          <match **>
            @type forward
            <server>
              host {{ td_agent_forward_host }}
              port {{ td_agent_forward_port }}
            </server>
          </match>

    - name: Enable and start td-agent
      systemd:
        name: td-agent
        enabled: yes
        state: restarted
